api/urls.py
from macrosurl import url
from django.conf.urls import include

from rest_framework import routers

from .asana.views import TaskViewSet


app_name = 'api'

asana_router = routers.DefaultRouter()
asana_router.register(r'tasks', TaskViewSet)


urlpatterns = [
    url(r'^asana/$', include(asana_router.urls)),
]

asana/urls.py
from macrosurl import url
from django.conf.urls import include

from . import views as asana_views


app_name = 'asana'

tasks_urlpatterns = [
    url(r'^$', asana_views.list_tasks, name="index"),
    url(r'^create/$', asana_views.create_task, name="create"),
    url(r'^:task_id/$$', asana_views.view_task, name="view"),
]

urlpatterns = [
    url(r'^tasks/$', include((tasks_urlpatterns, 'tasks'), namespace='tasks')),
]

vocdjango/urls.py
import os
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, LogoutView

from .views import Index


admin.site.site_header = "Todos Administration"
admin.site.site_title = "Todos Administration"
admin.site.index_title = "Welcome to Todos Administration"


urlpatterns = [
    url(r'^$', Index.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/login/',
        LoginView.as_view(template_name=os.path.join('auth', 'login.html')),
        name="login"),
    url(r'^auth/logout/', LogoutView.as_view(), name="logout"),

    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^asana/', include('asana.urls', namespace='asana'))
]

asana/models.py
from django.db import models
from django.utils import timezone


class TimestampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Task(TimestampModel):
    name = models.CharField(max_length=100, default="")

    start_time = models.DateTimeField(default=timezone.now)
    required_hours = models.PositiveIntegerField(default=1)

todos/models.py
from django.db import models
from django.utils import timezone


class TimestampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Task(TimestampModel):
    name = models.CharField(max_length=100, default="")

    start_time = models.DateTimeField(default=timezone.now())
    required_hours = models.PositiveIntegerField(default=1)

asana/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'start_time', 'required_hours')

api/asana/views.py
from rest_framework import viewsets
from rest_framework.response import Response

from asana.models import Task

from .serializers import TaskSerializer


class TaskViewSet(viewsets.ModelViewSet):
    serializer_class = TaskSerializer
    queryset = Task.objects.all()

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        serializer = self.get_serializer(queryset, many=True)
        return Response({'data': serializer.data})

asana/views.py
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import TaskForm

from .models import Task


@login_required
def list_tasks(request):
    if request.method == 'GET':
        context = {}
        return render(request, os.path.join('asana', 'tasks', 'index.html'), context)

    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            task = form.save()
            return redirect('asana:tasks:view', task_id=task.id)

        context = {'form': form}
        return render(request, os.path.join('asana', 'tasks', 'create.html'), context)


@login_required
def create_task(request):
    if request.method == 'GET':
        context = {
            'form': TaskForm()
        }
        return render(request, os.path.join('asana', 'tasks', 'create.html'), context)


@login_required
def view_task(request, task_id):
    if request.method == 'GET':
        context = {
            'task': get_object_or_404(Task, pk=task_id)
        }
        return render(request, os.path.join('asana', 'tasks', 'view.html'), context)

    if request.method == 'PUT':
        context = {}
        return render(request, os.path.join('asana', 'tasks', 'view.html'), context)

tasks/views.py
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import TaskForm

from .models import Task


@login_required
def list_tasks(request):
    if request.method == 'GET':
        context = {}
        return render(request, os.path.join('tasks', 'index.html'), context)

    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            task = form.save()
            return redirect('todos:view', task_id=task.id)

        context = {'form': form}
        return render(request, os.path.join('tasks', 'create.html'), context)


@login_required
def create_task(request):
    if request.method == 'GET':
        context = {
            'form': TaskForm()
        }
        return render(request, os.path.join('tasks', 'create.html'), context)


@login_required
def view_task(request, task_id):
    if request.method == 'GET':
        context = {
            'task': get_object_or_404(Task, pk=task_id)
        }
        return render(request, os.path.join('tasks', 'view.html'), context)

    if request.method == 'PUT':
        context = {}
        return render(request, os.path.join('tasks', 'view.html'), context)

todos/views.py
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import TaskForm

from .models import Task


@login_required
def list_tasks(request):
    if request.method == 'GET':
        context = {}
        return render(request, os.path.join('todos', 'index.html'), context)

    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            task = form.save()
            return redirect('todos:view', task_id=task.id)

        context = {'form': form}
        return render(request, os.path.join('todos', 'create.html'), context)


@login_required
def create_task(request):
    if request.method == 'GET':
        context = {
            'form': TaskForm()
        }
        return render(request, os.path.join('todos', 'create.html'), context)


@login_required
def view_task(request, task_id):
    if request.method == 'GET':
        context = {
            'task': get_object_or_404(Task, pk=task_id)
        }
        return render(request, os.path.join('todos', 'view.html'), context)

    if request.method == 'PUT':
        context = {}
        return render(request, os.path.join('todos', 'view.html'), context)

vocdjango/views.py
import os
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class Index(TemplateView):
    template_name = os.path.join('index.html')

vocdjango/templates/asana/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include "asana/head.html" %}
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}
        <div id="wrapper">
            <!-- Navigation -->
            {% include "asana/nav.html" %}

             <div id="page-wrapper">
                 <div class="row">
                     <div class="col-lg-12">
                         <h1 class="page-header">{% block title_page %}Demo Project{% endblock %}</h1>
                     </div>
                     <!-- /.col-lg-12 -->
                 </div>
                 <!-- /.row -->

                 <!-- /.row -->
                 {% block main %}{% endblock main %}
             </div>
         </div>

        {% include "asana/script.html" %}
        {% block foot %} {% endblock %}
        <script src="{% static 'tasks/dist/js/sb-admin-2.min.js' %}"></script>
    {% endblock %}
</body>
</html>

vocdjango/templates/asana/head.html
{% load staticfiles %}

<meta charset="UTF-8">
<title>{% block title %}Demo Project{% endblock %}</title>
<!-- Bootstrap Core CSS -->
<link href="{% static 'asana/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- MetisMenu CSS -->
<link href="{% static 'asana/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

<!-- Custom CSS -->
<link href="{% static 'asana/dist/css/sb-admin-2.min.css' %}" rel="stylesheet">

<!-- Morris Charts CSS -->
<link href="{% static 'asana/vendor/morrisjs/morris.css' %}" rel="stylesheet">

<!-- Custom Fonts -->
<link href="{% static 'asana/fonts/fontawesome.css' %}" rel="stylesheet" type="text/css">

<!-- jQuery -->
<script src="{% static 'asana/vendor/jquery/jquery.min.js' %}"></script>

vocdjango/templates/asana/index.html
{% extends 'asana/base.html' %}
{% load staticfiles i18n %}

{% block title %}Demo Project{% endblock %}

{% block head %}{% endblock %}

{% block title_page %}Asana{% endblock %}

{% block main %}
{% endblock main %}

{%block foot %}
{% endblock%}

vocdjango/templates/asana/nav.html
{% load staticfiles %}

<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Demo Project</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        {% if not user.is_anonymous %}
            <li>
                Hi {{user.username}}!
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-comment fa-fw"></i> New Comment
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                <span class="pull-right text-muted small">12 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-envelope fa-fw"></i> Message Sent
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-tasks fa-fw"></i> New Task
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">
                            <strong>See All Alerts</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.dropdown-alerts -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a></li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a></li>
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
        {% endif %}
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    {% include "asana/sidebar.html" %}
</nav>

vocdjango/templates/asana/script.html
{% load staticfiles %}

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'asana/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'asana/vendor/metisMenu/metisMenu.min.js' %}"></script>

<!-- Morris Charts JavaScript -->
<script src="{% static 'asana/vendor/raphael/raphael.min.js' %}"></script>

vocdjango/templates/asana/sidebar.html
{% load staticfiles %}

<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href=""><i class="fa fa-podcast fa-fw"></i> Tasks <span class="fa arrow"></a>
                <ul class="nav nav-second-level collapse">
                    <li>
                        <a href="{% url 'asana:tasks:create' %}"><i class="fas fa-plus-square fa-fw"></i> Create</a>
                        <a href="{% url 'asana:tasks:index' %}"><i class="fas fa-plus-square fa-fw"></i> List</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

vocdjango/templates/asana/tasks/create.html
{% extends 'asana/base.html' %}
{% load staticfiles i18n %}

{% block title %}Demo Project{% endblock %}

{% block head %}{% endblock %}

{% block title_page %}Create Task{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Task
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    {% include "asana/tasks/form.html" %}
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
{% endblock main %}

{%block foot %}
    {% csrf_token %}
    <script type="text/javascript">
    </script>
{% endblock%}

vocdjango/templates/asana/tasks/form.html
{% load staticfiles i18n %}
{% load widget_tweaks %}

<form role="form" action="{% url 'asana:tasks:index' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Name</label>
                {% render_field form.name|append_attr:"class=form-control" %}
                {{form.name.errors}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>When do you start?</label>
                {% render_field form.start_time|append_attr:"class=form-control" %}
                {{form.start_time.errors}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>How long do you need?</label>
                {% render_field form.required_hours|append_attr:"class=form-control" %}
                {{form.required_hours.errors}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <button class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

vocdjango/templates/asana/tasks/index.html
{% extends 'asana/base.html' %}
{% load staticfiles i18n %}

{% block title %}Demo Project{% endblock %}

{% block head %}
    <link href="{% static 'asana/vendor/datatables-plugins/dataTables.bootstrap.css' %}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{% static 'asana/vendor/datatables-responsive/dataTables.responsive.css' %}" rel="stylesheet">

    <!-- DataTables JavaScript -->
    <script src="{% static 'asana/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'asana/vendor/datatables-plugins/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'asana/vendor/datatables-responsive/dataTables.responsive.js' %}"></script>

    <script type="text/javascript">
        var tables = {};
    </script>
{% endblock %}

{% block title_page %}Tasks{% endblock %}

{% block main %}
    {% include "asana/tasks/table.html" with table_id="task-table" ajax_url="/api/asana/tasks/?format=json" only %}
{% endblock main %}

{%block foot %}
    {% csrf_token %}
    <script type="text/javascript">
        $(document).ready(function() {

        });
    </script>
{% endblock%}

vocdjango/templates/asana/tasks/table.html
{% load staticfiles i18n %}

<table width="100%" class="table table-striped table-bordered table-hover" id="{{table_id}}">
    <thead>
        <tr>
            <th>Name</th>
            <th>Start Time</th>
            <th>Required Hours</th>
            <th></th>
        </tr>
    </thead>
</table>
<!-- /.table-responsive -->

{% csrf_token %}
<script type="text/javascript">
    tables = tables || {};

    var opts = {
        columns: [
            {data: "name"},
            {data: "start_time"},
            {data: "required_hours"},
            {data: "url"}
        ],
        columnDefs: [
            {
                targets: 3,
                className: 'text-center',
                render: function ( data, type, row, meta ) {
                    return `<a href="${data}"><i class="fas fa-info-circle fa-fw"></i></a>`;
                }
            }
        ]
    }

    var ajax_url = "{{ajax_url|default:""}}";
    if (ajax_url != "") {
        opts.ajax = {
            url: ajax_url,
            contentType: "application/json",
            headers: { 'X-CSRFToken': jQuery("[name=csrfmiddlewaretoken]").val() },
            type: "GET"
        }
    }

    var data = "{{data|default:""}}";
    if (data != "") {
        opts.data = data;
    }

    tables["{{table_id}}"] = $("#{{table_id}}").DataTable(opts);
</script>

vocdjango/templates/asana/tasks/view.html
{% extends 'asana/base.html' %}
{% load staticfiles i18n %}

{% block title %}Asana Project{% endblock %}

{% block head %}{% endblock %}

{% block title_page %}Task {{task.id}}{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Task
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <form role="form">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <p class="form-control-static" id="id_name">{{task.name}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>When do you start?</label>
                                    <p class="form-control-static" id="id_start_time">{{task.start_time}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>How long do you need?</label>
                                    <p class="form-control-static" id="id_required_hours">{{task.required_hours}}</p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
{% endblock main %}

{%block foot %}
{% endblock%}

vocdjango/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Hi {{user.username}}!
</body>
</html>

vocdjango/templates/tasks/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include "tasks/head.html" %}
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}
        <div id="wrapper">
            <!-- Navigation -->
            {% include "tasks/nav.html" %}

             <div id="page-wrapper">
                 <div class="row">
                     <div class="col-lg-12">
                         <h1 class="page-header">{% block title_page %}Demo Project{% endblock %}</h1>
                     </div>
                     <!-- /.col-lg-12 -->
                 </div>
                 <!-- /.row -->

                 <!-- /.row -->
                 {% block main %}{% endblock main %}
             </div>
         </div>

        {% include "tasks/script.html" %}
        {% block foot %} {% endblock %}
        <script src="{% static 'tasks/dist/js/sb-admin-2.min.js' %}"></script>
    {% endblock %}
</body>
</html>

vocdjango/templates/tasks/create.html
{% extends 'tasks/base.html' %}
{% load staticfiles i18n %}

{% block title %}Demo Project{% endblock %}

{% block head %}{% endblock %}

{% block title_page %}Create Task{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Task
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    {% include "tasks/form.html" %}
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
{% endblock main %}

{%block foot %}
    {% csrf_token %}
    <script type="text/javascript">
    </script>
{% endblock%}

vocdjango/templates/tasks/form.html
{% load staticfiles i18n %}
{% load widget_tweaks %}

<form role="form" action="{% url 'tasks:index' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Name</label>
                {% render_field form.name|append_attr:"class=form-control" %}
                {{form.name.errors}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>When do you start?</label>
                {% render_field form.start_time|append_attr:"class=form-control" %}
                {{form.start_time.errors}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>How long do you need?</label>
                {% render_field form.required_hours|append_attr:"class=form-control" %}
                {{form.required_hours.errors}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <button class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

vocdjango/templates/tasks/index.html
{% extends 'tasks/base.html' %}
{% load staticfiles i18n %}

{% block title %}Demo Project{% endblock %}

{% block head %}{% endblock %}

{% block title_page %}Tasks{% endblock %}

{% block main %}
{% endblock main %}

{%block foot %}
{% endblock%}

vocdjango/templates/tasks/view.html
{% extends 'tasks/base.html' %}
{% load staticfiles i18n %}

{% block title %}Tasks Project{% endblock %}

{% block head %}{% endblock %}

{% block title_page %}Task {{task.id}}{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Task
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <form role="form">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <p class="form-control-static" id="id_name">{{task.name}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>When do you start?</label>
                                    <p class="form-control-static" id="id_start_time">{{task.start_time}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>How long do you need?</label>
                                    <p class="form-control-static" id="id_required_hours">{{task.required_hours}}</p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
{% endblock main %}

{%block foot %}
{% endblock%}

vocdjango/templates/todos/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include "todos/head.html" %}
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}
        <div id="wrapper">
            <!-- Navigation -->
            {% include "todos/nav.html" %}

             <div id="page-wrapper">
                 <div class="row">
                     <div class="col-lg-12">
                         <h1 class="page-header">{% block title_page %}Todos Project{% endblock %}</h1>
                     </div>
                     <!-- /.col-lg-12 -->
                 </div>
                 <!-- /.row -->

                 <!-- /.row -->
                 {% block main %}{% endblock main %}
             </div>
         </div>

        {% include "todos/script.html" %}
        {% block foot %} {% endblock %}
        <script src="{% static 'todos/dist/js/sb-admin-2.min.js' %}"></script>
    {% endblock %}
</body>
</html>

vocdjango/templates/todos/create.html
{% extends 'todos/base.html' %}
{% load staticfiles i18n %}

{% block title %}Todos Project{% endblock %}

{% block head %}{% endblock %}

{% block title_page %}Create Task{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Task
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    {% include "todos/form.html" %}
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
{% endblock main %}

{%block foot %}
    {% csrf_token %}
    <script type="text/javascript">
    </script>
{% endblock%}

vocdjango/templates/todos/index.html
{% extends 'todos/base.html' %}
{% load staticfiles i18n %}

{% block title %}Todos Project{% endblock %}

{% block head %}{% endblock %}

{% block title_page %}Tasks{% endblock %}

{% block main %}
{% endblock main %}

{%block foot %}
{% endblock%}

vocdjango/templates/todos/view.html
{% extends 'todos/base.html' %}
{% load staticfiles i18n %}

{% block title %}Todos Project{% endblock %}

{% block head %}{% endblock %}

{% block title_page %}Task {{task.id}}{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Task
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <form role="form">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Name</label>
                                    <p class="form-control-static" id="id_name">{{task.name}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>When do you start?</label>
                                    <p class="form-control-static" id="id_start_time">{{task.start_time}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>How long do you need?</label>
                                    <p class="form-control-static" id="id_required_hours">{{task.required_hours}}</p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
{% endblock main %}

{%block foot %}
{% endblock%}